name: build
on: [push]

jobs:
  main:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      # Checkout
      # ------------------------------------------------------------------------
      - uses: actions/checkout@v2

      # Activate Conda Environment
      # ----------------------------------------------------------------------
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: minilight
          environment-file: environment.yml

      # Build
      # ----------------------------------------------------------------------
      - run: python minilight.py cornellbox.ml.txt
      - run: mkdir -p images
      - run: mv cornellbox.ml.txt.ppm images/.

      # Deploy to gh-pages
      # ----------------------------------------------------------------------
      - run: rm .gitignore
      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
          PRESERVE: true