name: build
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} 
    steps:
      # Checkout
      # ------------------------------------------------------------------------
      - uses: actions/checkout@v2

      # Activate Conda Environment
      # ----------------------------------------------------------------------
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: minilight
          environment-file: environment.yml

      # ------------------------------------------------------------------------
        
      - name:
        run: sudo apt-get update && sudo-get upgrade && sudo apt-get install imagemagick

      # Build
      # ----------------------------------------------------------------------
      - run: python minilight.py cornellbox.ml.txt
      - run: python minilight.py cornellbox2.ml.txt
      - run: mkdir -p images
      - run: mv *.ppm images/.
      - run: cd images && convert cornellbox.ml.txt.ppm cornellbox.ml.txt.png && convert cornellbox2.ml.txt.ppm cornellbox2.ml.txt.png

      # Deploy to gh-pages
      # ----------------------------------------------------------------------
      - run: rm .gitignore
      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
          PRESERVE: true